config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  resources :posts 
  
  resources :comments, defaults: { format: 'html' }

  root "posts#index"


  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  #validates :user, :presence => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user (could be nil), and comment text
  # example in readme
  def self.build_from(obj, user_id, comment, first_name, last_name)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id,
      :first_name  => first_name,
      :last_name   => last_name
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :title, use: :slugged

	has_many :comments
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
	acts_as_commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  	def configure_permitted_parameters
    	devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name
    	devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@new_comment = build_comment(comment_params)
		respond_to do |format|
			if @new_comment.save
				make_child_comment
				format.html { redirect_to(:back, :notice => 'Comment was successfully added.')}
			else
				commentable = commentable_type.constantize.find(commentable_id)
				format.html { render template: 'posts/show', locals: {:@post => commentable} }
				format.json { render json: @new_comment.errors }
			end
		end
	end

	private
		def comment_params
			params.require(:comment).permit(:user, :first_name, :last_name, :body, :commentable_id, :commentable_type, :comment_id)
		end

		def commentable_type
			comment_params[:commentable_type]
		end

		def commentable_id
			comment_params[:commentable_id]
		end

		def comment_id
			comment_params[:comment_id]
		end

		def body
			comment_params[:body]
		end

		def make_child_comment
			return "" if comment_id.blank?

			parent_comment = Comment.find comment_id
			@new_comment.move_to_child_of(parent_comment)
		end

		def build_comment(comment_params)
			if current_user.nil?
      			user_id = nil 
      			first_name =  comment_params[:first_name]
      			last_name = comment_params[:last_name]
    		else
      			user_id = current_user.id
      			first_name = current_user.first_name
      			last_name = current_user.last_name
    		end
    		commentable = commentable_type.constantize.find(commentable_id)
			Comment.build_from(commentable, user_id, comment_params[:body],
						first_name, last_name)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
		
	end

	def sociallinks
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.friendly.find(params[:id])
		@new_comment = Comment.build_from(@post, nil, "", "", "")
	end

	def edit
		@post = Post.friendly.find(params[:id])
	end

	def update
		@post = Post.friendly.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def destroy
		@post = Post.friendly.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?

  protected

  	def one_user_registered?
    	if ((User.count == 1) & (user_signed_in?))
      		redirect_to root_path
    	elsif User.count == 1
      		redirect_to new_user_session_path
    	end  
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def displayed_name(comment)
		comment.user ? comment.user.first_name + " " + comment.user.last_name :
		"#{comment.first_name} #{comment.last_name}"
	end

	def markdown(text)
		options = {
			filter_html:     true,
			hard_wrap:       true, 
			prettify:        true,
			link_attributes: { rel: 'nofollow', target: "_blank" },
			space_after_headers: true, 
			fenced_code_blocks: true
		}

		extensions = {
			autolink:           true,
			superscript:        true,
			disable_indented_code_blocks: true,
			tables:             true,
			strikethrough:     true
		}

		renderer = Redcarpet::Render::HTML.new(options)
		markdown = Redcarpet::Markdown.new(renderer, extensions)

		markdown.render(text).html_safe
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for @new_comment do |f| %>  
	<% if @new_comment.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@new_comment.errors.count, "error") %> encountered, please check your input.</h2>

			<ul>
				<% @new_comment.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
  <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
  <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
  <%= f.hidden_field :user, value: current_user %>
  <div class="field">
  	<%= f.label :first_name %>:
  	<%= f.text_field :first_name %>
  </div>

  <div class="field">
  	<%= f.label :last_name %>:
  	<%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.text_area :body %>
  </div>
  <br>

  <div class="field">
    <%= f.submit "Post comment" %>
  </div>
<% end %>  

app/views/comments/_reply.html.erb
<% comments.each do |comment| %>  
<div class="comments-show">
  <div class="comment">
    <p id="author"><%= displayed_name(comment) %> - <%= time_ago_in_words(comment.created_at) %> ago</p><br>
    <p id="comment-body"><%= comment.body %></p><br>
    <div class="comment-nav">
      <span class="text"><a href="#" class="comment-reply">Reply</a></span>
    </div>
    <div class="reply-form">
      <%= simple_form_for @new_comment do |f| %>
      <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
      <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
      <%= f.hidden_field :comment_id, value: comment.id %>
      <%= f.hidden_field :user, value: current_user %>
      <div class="field">
        <%= f.label :first_name %>:
        <%= f.text_field :first_name %>
      </div>

      <div class="field">
        <%= f.label :last_name %>:
        <%= f.text_field :last_name %>
      </div>
      <div class="field">
        <%= f.text_area :body %>
      </div>
      <br>
      <div class="field">
        <%= submit_tag "Post Reply" %>
      </div>
      <% end %>
    </div>
  </div>
  <%= render partial: "comments/reply", locals: {comments: comment.children} %>
</div>
<% end %>  

app/views/comments/_template.html.erb
<div class="comments-header">  
  <h4>
    <%= pluralize(commentable.comment_threads.count, 'comment') %>
  </h4>
</div>
<div class="comments-container">  
  <%= render partial: "comments/reply", locals: {comments: commentable.root_comments} %>
</div>  

<%= render partial: "comments/form", locals: {new_comment: new_comment} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag	 'application', 'http://fonts.googleapis.com/css?family=Railway:400, 700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="sidebar">
	<div id="logo">
		<%= link_to root_path do %>
			<% image_tag "logo.png" %>
		<% end %>
	</div>

	<ul>
		<li class="category">Website</li>
		<li><%= link_to "Blog", root_path %></li>
		<li><%= link_to "About", about_path %></li>
	</ul>

	<ul>
		<li class="category">Social</li>
		<li><a href="https://www.twitter.com/yfe666">Twitter</a></li>
		<li><a href="https://github.com/crazyyi">Github</a></li>
		<li><a href="http://www.gunghosolutions.com">Business</a></li>
	</ul>

	<% if !user_signed_in? %>
		<p class="sign_in"><%= link_to "Admin Login", user_session_path %></p>
	<% else %>
		<p class="sign_in">Welcome back, <%= current_user.first_name + " " + current_user.last_name %></p>
	<% end %>
</div>

<div id="main_content">
	<div id="header">
		<% if current_page?(root_path) %>
			<p>All Posts</p>
		<% elsif current_page?(about_path) %>
			<p>About</p>
		<% else %>
			<%= link_to "Back to All Posts", root_path %>
		<% end %>

		<% if user_signed_in? %>
			<div class="buttons">
				<button class="button"><%= link_to "New Post", new_post_path %></button>
				<button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
			</div>
		<% end %>
	</div>

	<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class:"alert") %>
	<% end %>
<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		
	</div>

	<div id="content">
		<h1>Hi, my name is Aaron Zeng. I am a software engineer.</h1>
		<p>I love building web apps using Ruby on Rails. I have built a lot of apps in RoR including this Web Blog. </p>
		<p>In fact this is one of the experiment projects I built when I was learning RoR. Feel free to drop me a message if you are interested in my blog.</p>
		<p>I am based in Guangzhou, China. But sometimes I like to get tanned on the beach of Thailand or relax on the beach of Australia :) </p>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> encountered, please check your input.</h2>

			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %><br>
	</p>

	<p>
		<%= f.submit "Submit" %>
	</p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>

</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title">
			<%= link_to post.title, post %>
		</h2>

		<p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>

			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %><br>
	</p>

	<p>
		<%= f.submit "Submit" %>
	</p>
	<% end %>

</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> Ago 

		<% if user_signed_in? %>
			| <%= link_to 'Edit', edit_post_path(@post) %>
			| <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
		<% end %>
	</p>

	<p class="body">
		<%= markdown(@post.body) %>
	</p>

	<div id="comments">
		<%= render partial: "comments/template", locals: {commentable: @post, new_comment: @comment} %> 
	</div>

</div>

app/views/shared/_error_messages.html.erb
<% if messages.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(messages.errors.count, "error") %> encountered, please check your input.</h2>

			<ul>
				<% messages.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
<% end %>